// Generated by scripts/generate-metadata.cjs from package.json.
export const APP_METADATA = {
  "name": "Comiscopio",
  "version": "0.3.0",
  "description": "Visor de cómics y manga con lectura LTR, RTL y vertical, miniaturas y progreso guardado.",
  "author": "Rigoberto L. Salgado Reyes <rlsalgado2006@gmail.com>",
  "license": "AGPL-3.0-or-later",
  "repositoryUrl": "https://github.com/Rigo85/Comiscopio"
} as const;
